Vagrant.configure(2)  do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "graylog"

  config.vm.network :forwarded_port, guest: 9000, host: 9000
  config.vm.network :forwarded_port, guest: 12900, host: 12900
  config.vm.network :forwarded_port, guest: 12201, host: 12201, protocol: 'udp'
  config.vm.network :forwarded_port, guest: 12201, host: 12201, protocol: 'tcp'
  
  config.vm.synced_folder "../work", "/var/work"
  config.ssh.insert_key = false
  
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
  end

  
  
  $script = <<SCRIPT
  apt-get install -y python-software-properties debconf-utils
  add-apt-repository -y ppa:webupd8team/java
  wget -O - http://packages.elasticsearch.org/GPG-KEY-elasticsearch | sudo apt-key add -
  echo 'deb http://packages.elasticsearch.org/logstash/1.5/debian stable main' | sudo tee /etc/apt/sources.list.d/logstash.list
  apt-get update
  echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | sudo debconf-set-selections
  apt-get install -y oracle-java8-installer
  echo 'Going to download Graylog...'
  curl -s -L -O https://packages.graylog2.org/releases/graylog2-omnibus/ubuntu/graylog_latest.deb
  dpkg -i graylog_latest.deb
  rm graylog_latest.deb
  graylog-ctl reconfigure
  apt-get install logstash
SCRIPT

  config.vm.provision "shell", inline: $script
end
